version: '2.2'

services:
  php73fpm_clinica:
    container_name: php73fpm_clinica
    image: php73fpm:latest
    volumes:
      - .:/var/www/html
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    build:
        context: ./.docker/dockerfile_php73fpm
        dockerfile: ./Dockerfile
  clinica:
    container_name: clinica
    image: 'clinica'
    working_dir: /var/www/html
    ports:
      - 8081:80
    volumes:
      - .:/var/www/html
    entrypoint: [ "/bin/sh" , "entrypoint.sh" ]
    restart: always
    links:
      - php73fpm_clinica
    depends_on:
      - php73fpm_clinica
    environment:
      - APP_ENV_DOCKER=local
    tty: true
    command: [nginx, '-g', 'daemon off;']
    build:
        context: ./.docker/dockerfile_nginx
        dockerfile: ./Dockerfile
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      - postgres-network
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "frederico.cruz@datacruz.com.br"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - "16543:80"
    depends_on:
      - php73fpm_clinica
    networks:
      - postgres-network
networks: 
  postgres-network:
    driver: bridge
volumes:
  db:
    driver: local
